/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package io.github.libai8723;

import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import static java.awt.event.KeyEvent.VK_ESCAPE;


/**
 *
 * @author libai8723
 */
public class MyJDialog extends javax.swing.JDialog {

    /**
     * Creates new form MyJDialog
     */
    public MyJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setProperSize();
        setCenter();
    }
    
    private void setCenter(){
        GraphicsDevice gd = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
        int srnWidth = gd.getDisplayMode().getWidth();
        int srnHeight = gd.getDisplayMode().getHeight();
        int width = this.getWidth();
        int height = this.getHeight();
        this.setLocation((srnWidth-width)/2,(srnHeight - height)/2);
    }
    
    private void setProperSize(){
        int fontSize = 12;
        GraphicsDevice gd = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
        int srnWidth = gd.getDisplayMode().getWidth();
        
        int width = 360;
        
        if(srnWidth > 1280 && srnWidth <= 1920){
            fontSize = 18;
            width = 480;
            System.out.println("small screen");
              
        }else if(srnWidth > 1920){
            fontSize = 24;
            width = 600;
            System.out.println("big screen");
        }
        
        java.awt.Font ff = new java.awt.Font("微软雅黑", 0, fontSize);
        this.dieNameTextField.setFont(ff);
        this.okButton.setFont(ff);
        this.cancelButton.setFont(ff);
        
        this.setSize(width, this.getHeight());
        
    }
    
    public String getInputString(){
        this.setVisible(true);
        this.dispose();
        return this.dieNameTextField.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        dieNameTextField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Input the Dirname");
        setPreferredSize(new java.awt.Dimension(480, 240));

        dieNameTextField.setFont(new java.awt.Font("微软雅黑", 0, 24)); // NOI18N
        dieNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dieNameTextFieldActionPerformed(evt);
            }
        });
        dieNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dieNameTextFieldKeyPressed(evt);
            }
        });
        getContentPane().add(dieNameTextField, java.awt.BorderLayout.CENTER);

        okButton.setFont(new java.awt.Font("微软雅黑", 0, 24)); // NOI18N
        okButton.setText("Confirm");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        jPanel1.add(okButton);

        cancelButton.setFont(new java.awt.Font("微软雅黑", 0, 24)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cancelButton);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>                        

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        System.exit(1);
    }                                            

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {                                         
        this.setVisible(false);
    }                                        

    private void dieNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        this.okButtonActionPerformed(evt);
    }                                                

    private void dieNameTextFieldKeyPressed(java.awt.event.KeyEvent evt) {                                            
        if(evt.getKeyCode() == VK_ESCAPE){
            System.exit(1);
        }
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
                MyJDialog dialog = new MyJDialog(null, true);
                System.out.println(dialog.getInputString());
                
                
                
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField dieNameTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton okButton;
    // End of variables declaration                   
}
